<a href="https://colab.research.google.com/github/Taekil/TensorFLowStudyNote/blob/master/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html

tensors provide a unified wya to train neural networks for more complex data sets.

In [2]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
# tensor generated
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_ones = torch.ones_like(x_data) # keep shape and datatype
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # override
print(f"Ones Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[0.8913, 0.6043],
        [0.2337, 0.0606]]) 



In [3]:
# random or constant
# shape is the tuple to express dimension
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random: \n {rand_tensor}\n")
print(f"Ones: \n {ones_tensor}\n")
print(f"Zeros: \n {zeros_tensor}\n")

Random: 
 tensor([[0.6699, 0.4394, 0.6460],
        [0.8459, 0.9755, 0.7451]])

Ones: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



tensor's attribute: Shape and datatype, the saving location.

In [4]:
tensor = torch.rand(3,4)
# attribute
print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device of tensor: {tensor.device}")

#

shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of tensor: cpu
